DEFAULT_COLUMNS = [
    "TS",
    "Bus",
    "ID",
    "LEN",
    "DATA",
    "B0",
    "B1",
    "B2",
    "B3",
    "B4",
    "B5",
    "B6",
    "B7",
]

DEFAULT_OPTIONS = {
    "dbc_modes": ["exact", "j1939"],
    "signal_match_modes": ["exact", "j1939", "bam"],
    "decode_value_modes": ["Scaled", "Raw"],
    "decode_value_scaled": "Scaled",
    "decode_value_raw": "Raw",
    "filter_types": [
        "None",
        "Moving Average",
        "Exponential Moving Average",
        "Median",
        "Gaussian",
        "Savitzky-Golay",
    ],
    "filter_none_type": "None",
    "filter_window_types": ["Moving Average", "Median", "Savitzky-Golay"],
    "filter_alpha_type": "Exponential Moving Average",
    "filter_sigma_type": "Gaussian",
    "filter_polyorder_type": "Savitzky-Golay",
    "line_styles": ["Solid", "Dashed", "Dotted"],
    "data_types": ["uint", "int", "float32"],
    "default_data_type": "uint",
    "float_data_type": "float32",
    "ssh_interfaces": ["can0", "can1"],
}
