UI_STRINGS = {
    "dbc_manager_title": "DBC Manager",
    "dbc_empty": "No DBC loaded",
    "dbc_enable_header": "Enable",
    "dbc_name_header": "DBC",
    "dbc_type_header": "Type",
    "dbc_status_header": "Status",
    "dbc_load": "Load DBC...",
    "dbc_delete": "Delete DBC",
    "dbc_load_title": "Load DBC",
    "dbc_files_filter": "DBC / PGN CSV files (*.dbc *.csv);;DBC files (*.dbc);;PGN CSV files (*.csv);;All files (*)",
    "dbc_loading": "Loading DBC...",
    "dbc_loading_named": "Loading DBC: {name}...",
    "dbc_status_loading": "Loading",
    "dbc_status_ok": "OK",
    "dbc_delete_confirm_title": "Delete DBC",
    "dbc_delete_confirm_message": "Remove '{name}' from the DBC list?",
    "dbc_loading_title": "Loading",
    "dbc_load_failed_title": "DBC load failed",
    "dbc_load_failed_message": "Unable to load DBC:\n{error}",
    "dbc_mode_switch_warning_title": "Switching to exact ID matching",
    "dbc_mode_switch_warning_message": "'{name}' was matched by PGN (J1939 mode). Exact ID matching only works if this DBC defines a real, fixed frame ID -- switching can silently stop matching any live traffic.",
    "dbc_overlap_warning_title": "Overlapping signals",
    "dbc_overlap_warning_message": "'{name}' was loaded. {count} signal pair(s) share overlapping bytes within the same PGN -- both were kept, but double-check the byte offsets/lengths in your source CSV if this is unexpected:",
    "dbc_overlap_warning_line": "  - {message}: {signal_a} overlaps {signal_b}",
    "graph_settings_title": "Graph settings",
    "graph_settings_signal_tab": "Signal",
    "graph_settings_dbc_tab": "DBC",
    "graph_settings_graph_tab": "Graph",
    "graph_settings_filters_tab": "Filters",
    "ok": "OK",
    "delete": "Delete",
    "duplicate": "Duplicate",
    "invalid_name_title": "Invalid name",
    "invalid_name_message": "Signal name cannot be empty.",
    "duplicate_signal_title": "Duplicate signal",
    "duplicate_signal_message": "A signal named '{name}' already exists.",
    "signal_filter_title": "Signal filter",
    "filter_type_label": "Filter type",
    "window_label": "Window (MA/Median/SG)",
    "alpha_label": "Alpha (EMA)",
    "sigma_label": "Sigma (Gaussian)",
    "polyorder_label": "Polyorder (Savitzky-Golay)",
    "decimals_label": "Decimals (Truncate/Round)",
    "graph_style_title": "Graph style",
    "select_color": "Select color",
    "color_label": "Color",
    "line_style_label": "Line style",
    "line_width_label": "Line width",
    "marker_enabled_label": "Show points",
    "marker_shape_label": "Point shape",
    "marker_size_label": "Point width",
    "marker_max_points_label": "Max points",
    "marker_max_points_tooltip": "Max points drawn per view (higher = more detail, slower)",
    "marker_color_label": "Point color",
    "decode_dbc_group_title": "DBC",
    "decode_group_title": "CAN decode",
    "dbc_label": "DBC",
    "message_label": "Message",
    "signal_label": "Signal",
    "value_label": "Value",
    "apply_dbc": "GetDecode",
    "show_all_ids": "Show all IDs",
    "signal_name_label": "Signal name",
    "can_id_label": "CAN ID",
    "source_label": "Source",
    "match_mode_label": "Match mode",
    "pgn_label": "PGN",
    "start_bit_label": "Start bit",
    "length_label": "Length",
    "endianness_label": "Endianness",
    "data_type_label": "Data type",
    "scale_label": "Scale",
    "offset_label": "Offset",
    "mux_start_label": "MUX Start",
    "mux_bytes_label": "MUX bytes",
    "mux_value_label": "MUX value",
    "little_endian": "Little Endian",
    "big_endian": "Big Endian",
    "add_new_graph": "Add new graph",
    "add_last_graph": "Add last graph",
    "main_window_title": "Canlytics",
    "menu_theme": "Theme",
    "load_log_title": "Load CAN log",
    "append_log_title": "Append CAN log",
    "log_files_filter": "Log files (*.log *.txt);;All files (*)",
    "loading_log": "Loading CAN log...",
    "loading_title": "Loading",
    "failed_prefix": "Failed: {error}",
    "cancel": "Cancel",
    "menu_file": "File",
    "menu_load_log": "Load Log",
    "menu_append_log": "Append Log",
    "menu_clear_log": "Clear log",
    "menu_save_log": "Save Log",
    "menu_load_dbc": "Load DBC...",
    "menu_settings": "Settings",
    "menu_time_config": "Time Config...",
    "menu_time_filter": "Time filter...",
    "menu_tools": "Tools",
    "menu_add_plot": "Add new graphic window",
    "menu_connection": "Connection...",
    "menu_analyze_data": "Analyze Data",
    "menu_candidate_interpretations": "Candidate Interpretations",
    "menu_mux_detection": "MUX Detection",
    "menu_signal_coverage": "Signal Scan",
    "menu_hmi_video_extractor": "HMI Video Extractor",
    "select_all": "Select all",
    "select_none": "Select none",
    "can_id_panel_can_ids": "CAN IDs",
    "can_id_panel_interpretation": "Interpretation",
    "can_id_search_placeholder": "Search CAN ID...",
    "interpret_frames": "Interpret frames",
    "interpret_tooltip": "Load/enable a DBC to interpret frames",
    "expand_all": "Expand all",
    "collapse_all": "Collapse all",
    "cursor_settings_title": "Cursor settings",
    "cursor_settings_menu": "Cursor settings...",
    "cursor_behavior_group": "Behavior",
    "cursor_mode_group": "Cursor mode",
    "cursor_display_group": "Display",
    "cursor_enabled": "Show cursor",
    "cursor_follow_latest": "Follow latest data",
    "cursor_snap_to_sample": "Snap to sample",
    "cursor_dual": "Dual cursor (A/B)",
    "cursor_active": "Active cursor",
    "cursor_a": "Cursor A",
    "cursor_b": "Cursor B",
    "cursor_show_time": "Show time",
    "cursor_show_values": "Show values",
    "cursor_show_delta": "Show delta (A/B)",
    "cursor_copy_snapshot": "Copy snapshot",
    "time_filter_title": "Time filter",
    "time_filter_group": "Time range",
    "time_filter_timestamp_label": "Timestamp",
    "time_filter_date_label": "Date",
    "time_filter_ts_from": "Timestamp from",
    "time_filter_ts_to": "Timestamp to",
    "time_filter_date_from": "Date from: YYYY-MM-DD HH:MM:SS",
    "time_filter_date_to": "Date to: YYYY-MM-DD HH:MM:SS",
    "time_filter_date_disabled_tooltip": "Date filter requires a configured timezone in TimeConfig.",
    "connection_title": "Connection",
    "connection_type_label": "Connection type",
    "connection_mode_label": "Settings",
    "connection_start": "Start",
    "connection_stop": "Stop",
    "connection_save_log": "Save Log",
    "connection_status_idle": "Idle",
    "connection_status_label": "Status",
    "connection_error_prefix": "Error: {error}",
    "connection_no_data_to_save": "No CAN data to save",
    "connection_log_saved_prefix": "Saved log: {path}",
    "connection_offset_sign_tooltip": "Toggle offset sign (+/−)",
    "connection_offset_tooltip": "Offset added to every recorded timestamp (HH:MM:SS)",
    "connection_time_config_button": "Time Config…",
    "connection_time_config_tooltip": "Configure timezone for timestamp display",
    "connection_show_hide_passphrase_tooltip": "Show / hide passphrase",
    "connection_ssh_clock_waiting": "Device: waiting for CAN frames…",
    "connection_kvaser_clock_waiting": "Device: available when streaming",
    "connection_clock_device_prefix": "Device: {value}",
    "connection_clock_pc_prefix": "PC: {value}",
    "real_time_analysis_label": "Real-Time Analysis",
    "real_time_analysis_mode_label": "Real-Time Analysis",
    "real_time_detect_changes_label": "Track Changes",
    "real_time_detect_changes_mode_label": "Change Detection",
    "real_time_show_bits_label": "Show Bits",
    "real_time_data_format_mode_label": "Data Format",
    "real_time_refresh_interval_label": "Refresh Interval",
    "show_only_changing_label": "Changes Only",
    "show_only_changing_mode_label": "Change Filter",
    "show_only_changing_tooltip": "Show only IDs that have changed since the last reset.",
    "show_only_changing_disabled_tooltip": "Requires Track Changes.",
    "mux_configuration_label": "MUX Configuration",
    "mux_configuration_placeholder": "Byte indexes, e.g. 0 or 0,1",
    "mux_configuration_button": "Edit MUX Rules",
    "mux_configuration_dialog_title": "MUX Configuration",
    "mux_configuration_can_id": "CAN ID",
    "mux_configuration_len": "LEN",
    "mux_configuration_bytes": "MUX Bytes",
    "mux_configuration_add": "Add Rule",
    "mux_configuration_remove": "Remove Rule",
    "reset_change_detection": "Reset Realtime",
    "ssh_host_placeholder": "192.168.x.x",
    "ssh_username_default": "root",
    "ssh_key_placeholder": "Select private key file",
    "ssh_browse": "Browse",
    "ssh_start": "Start",
    "ssh_stop": "Stop",
    "ssh_status_idle": "Idle",
    "ssh_ip_host_label": "IP/Host",
    "ssh_username_label": "Username",
    "ssh_key_file_label": "Key file",
    "ssh_key_passphrase_label": "Key passphrase",
    "ssh_can_interface_label": "CAN interface",
    "ssh_status_label": "Status",
    "ssh_select_key_title": "Select private key",
    "ssh_key_files_filter": "Key files (*);;All files (*)",
    "ssh_host_required": "Host required",
    "kvaser_interface_label": "SerialBus Device Type",
    "kvaser_channel_label": "Port",
    "kvaser_bitrate_label": "Bitrate",
    "kvaser_channel_placeholder": "J2534 for Kvaser Hardware",
    "kvaser_bitrate_placeholder": "500000",
    "kvaser_extra_placeholder": "driver=\"J2534 for Kvaser Hardware\", serial=12345",
    "kvaser_interface_required": "Bus type / backend required",
    "kvaser_bitrate_invalid": "Bitrate must be a valid integer",
    "replay_file_label": "Replay file",
    "replay_speed_label": "Replay speed",
    "replay_browse": "Browse",
    "replay_file_placeholder": "Select candump or Kvaser log file",
    "replay_file_required": "Replay file required",
    "replay_speed_invalid": "Replay speed must be a valid positive number",
    "replay_select_title": "Select replay log",
    "replay_status_prefix": "Replay",
    "analyze_data_title": "Analyze Data",
    "analyze_data_stats_label": "Statistics",
    "analyze_data_bytes_label": "Bytes",
    "analyze_data_mux_case_label": "MUX Case",
    "analyze_data_stats_metric": "Metric",
    "analyze_data_stats_value": "Value",
    "analyze_data_bytes_all": "All",
    "analyze_data_bytes_none": "None",
    "analyze_data_toolbar_title": "Settings",
    "analyze_data_time_config_action": "Time Config",
    "analyze_data_time_config_tooltip": "Configure timestamp display format",
    "analyze_data_time_filter_action": "Time filter",
    "analyze_data_time_filter_tooltip": "Filter data by time range",
    "about_dialog_title": "About Canlytics",
    "about_dialog_version_prefix": "Version {version}",
    "about_dialog_description": "CAN bus log analyzer & visualizer",
    "ribbon_collapse_tooltip": "Anchor ribbon  (F10)",
    "ribbon_realtime_tooltip": "Open Real-Time Analysis (available when connected)",
    "fft_window_title": "FFT — Frequency Analysis",
    "fft_window_title_range_prefix": "FFT — {range_label}",
    "fft_window_db_tooltip": "Switch between linear amplitude and dB (20·log10)",
    "decode_pick_mux_tooltip": "Click a matrix cell to set the MUX start byte",
    "decode_no_data_bytes": "No data — 0 bytes",
    "candidate_interpretations_title": "Candidate Interpretations",
    "candidate_interpretations_can_ids": "CAN IDs",
    "candidate_interpretations_mux_case": "MUX Case",
    "candidate_interpretations_parameters": "Parameters",
    "candidate_interpretations_bit_length": "Bit Length",
    "candidate_interpretations_min_length": "Min Length",
    "candidate_interpretations_max_length": "Max Length",
    "candidate_interpretations_granularity": "Granularity",
    "candidate_interpretations_sensitivity": "Sensitivity",
    "candidate_interpretations_sensitivity_low": "More permissive",
    "candidate_interpretations_sensitivity_high": "More strict",
    "candidate_interpretations_endianness": "Endianness",
    "candidate_interpretations_value_type": "Value Type",
    "candidate_interpretations_recalculate": "Recalculate Candidate Signals",
    "candidate_interpretations_advanced_parameters": "Configuration",
    "candidate_interpretations_candidates": "Candidate Signals",
    "candidate_interpretations_empty_ids": "Load a CAN log to choose IDs.",
    "candidate_interpretations_empty_candidates": "No candidate signals yet. Select CAN IDs and recalculate.",
    "candidate_interpretations_empty_filtered": "No candidate signals match the active filters.",
    "candidate_interpretations_details": "Selected Interpretation",
    "candidate_interpretations_try_both": "Try Both",
    "candidate_interpretations_little_endian": "Little Endian",
    "candidate_interpretations_big_endian": "Big Endian",
    "candidate_interpretations_try_all": "Try All",
    "candidate_interpretations_unsigned": "Unsigned",
    "candidate_interpretations_signed": "Signed",
    "candidate_interpretations_float32": "Float32",
    "candidate_interpretations_loading": "Loading candidate interpretations...",
    "candidate_interpretations_recalculating": "Recalculating candidate interpretations...",
    "candidate_filters_title": "Candidate Filters",
    "menu_candidate_filters": "Filters...",
    "candidate_show_details": "Show details panel",
    "mux_detection_title": "MUX Detection",
    "mux_detection_signals": "Signals to Analyze",
    "mux_detection_conditions": "Detection Conditions",
    "mux_detection_analyze": "Analyze Selected Signals",
    "mux_detection_loading": "Analyzing possible MUX values...",
    "mux_detection_results": "Analyzed Signals",
    "mux_detection_candidates": "Possible MUX Candidates",
    "mux_detection_details": "Candidate Details",
    "mux_detection_hide_without_candidates": "Hide signals without MUX candidates",
    "mux_detection_summary_section": "Summary",
    "mux_detection_relationships_section": "Relationships",
    "mux_detection_states_section": "States Information",
    "mux_detection_state_periods_section": "State Periods",
    "mux_detection_state_value": "State",
    "mux_detection_state_count": "Count",
    "mux_detection_period_state": "State",
    "mux_detection_period_median": "Median",
    "mux_detection_period_mean": "Mean",
    "mux_detection_period_cv": "CV",
    "mux_detection_use_change_rate": "Require change activity",
    "mux_detection_use_unique_ratio": "Require discrete value ratio",
    "mux_detection_use_periodicity": "Require per-state periodicity",
    "mux_detection_use_nmi": "Require dependency on other bytes",
    "mux_detection_use_entropy": "Use entropy in score",
    "mux_detection_use_window_entropy": "Use window entropy",
    "mux_detection_use_bitfields": "Analyze bitfields too",
    "mux_detection_require_early_states": "Require states to appear early in the capture",
    "mux_detection_strictness": "Strictness",
    "mux_detection_strictness_low": "More permissive",
    "mux_detection_strictness_high": "More strict",
    "signal_coverage_title": "Signal Scan",
    "signal_coverage_analyze": "Analyze Loaded Signals",
    "signal_coverage_loading": "Scanning DBC signals...",
    "signal_coverage_filters_button": "Filters",
    "signal_coverage_filters_title": "Signal Scan Filters",
    "signal_coverage_exclude_no_data": "Hide no data",
    "signal_coverage_only_changing": "Only changing",
    "signal_coverage_byte_aligned_only": "Only byte-aligned",
    "signal_coverage_hide_pdu1": "Hide PDU1",
    "signal_coverage_search_placeholder": "Search parameter or message...",
    "signal_coverage_status": "{shown} of {total} signals with data",
    "signal_coverage_col_parameter": "Parameter",
    "signal_coverage_col_message": "Message",
    "signal_coverage_col_dbc": "DBC",
    "signal_coverage_col_can_id": "CAN ID",
    "signal_coverage_col_pgn": "PGN",
    "signal_coverage_col_has_data": "Has Data",
    "signal_coverage_has_data_yes": "Yes",
    "signal_coverage_has_data_no": "No",
    "signal_coverage_col_last_value": "Last Value",
    "signal_coverage_col_unit": "Unit",
    "signal_coverage_col_decoding": "Decoding",
    "signal_coverage_col_frames": "Frames",
    "signal_coverage_col_unique": "Unique",
    "signal_coverage_col_min": "Min",
    "signal_coverage_col_max": "Max",
    "signal_coverage_col_mean": "Mean",
    "signal_coverage_col_description": "Description",
    "hmi_video_title": "HMI Video Extractor",
    "hmi_video_load": "Load Video...",
    "hmi_video_draw_roi": "Draw ROI",
    "hmi_video_draw_anchor": "Draw Anchor",
    "hmi_video_delete_roi": "Delete ROI",
    "hmi_video_rois": "ROIs",
    "hmi_video_processing": "Processing",
    "hmi_video_results": "Results",
    "hmi_video_plots": "Plots",
    "hmi_video_logs": "Logs",
    "hmi_video_process": "Process Video",
    "hmi_video_files_filter": "Video files (*.mp4 *.avi *.mov *.mkv);;All files (*)",
    "hmi_roi_name": "Name",
    "hmi_roi_unit": "Unit",
    "hmi_roi_profile": "OCR Profile",
    "hmi_min_confidence": "Min Confidence",
    "hmi_roi_enabled": "Enabled",
    "hmi_anchor_select_roi_first": "Select a ROI first, then draw its anchor block.",
    "hmi_process_start": "Start frame",
    "hmi_process_end": "End frame",
    "hmi_process_step": "Frame step",
    "hmi_process_temporal_penalty": "Apply temporal confidence penalty",
    "candidate_tag_placeholder": "Signal name / meaning...",
    "candidate_tag_button": "Tag",
    "candidate_untag_button": "Remove Tag",
    "candidate_export_tags": "Export Tags",
    "candidate_import_tags": "Import Tags",
    "candidate_export_tags_title": "Export Signal Tags",
    "candidate_import_tags_title": "Import Signal Tags",
    "candidate_tags_exported": "Exported {count} tag(s)",
    "candidate_tags_imported": "Imported {count} tag(s)",
    "candidate_no_tags": "No tags to export.",
    "candidate_filter_all": "All signals",
    "candidate_hide_tagged": "Hide tagged",
    "candidate_show_only_tagged": "Show only tagged",
    "candidate_amp_filter": "Amplitude Filter",
    "candidate_frames_filter": "Frames Count Filter",
    "candidate_frames_min": "Min frames",
    "candidate_frames_max": "Max frames",
    "menu_candidate_tools": "Tools",
    # Ribbon bar
    "ribbon_tab_home": "Home",
    "ribbon_tab_analysis": "Analysis",
    "ribbon_tab_settings": "Settings",
    "ribbon_group_file": "File",
    "ribbon_group_dbc": "DBC",
    "ribbon_group_stream": "Stream",
    "ribbon_group_analysis": "Analysis",
    "ribbon_group_time": "Time",
    "ribbon_group_display": "Display",
    "ribbon_btn_load_log": "Load Log",
    "ribbon_btn_append": "Append",
    "ribbon_btn_save": "Save",
    "ribbon_btn_clear": "Clear",
    "ribbon_btn_dbc_manager": "DBC Manager",
    "ribbon_btn_connection": "Connect",
    "ribbon_btn_add_plot": "Add Plot",
    "ribbon_btn_analyze": "Analyze",
    "ribbon_btn_candidates": "Candidates",
    "ribbon_btn_signal_coverage": "Scan",
    "ribbon_btn_time_config": "Time Config",
    "ribbon_btn_time_filter": "Time Filter",
    "ribbon_btn_theme": "Theme",
    "ribbon_btn_real_time": "Real Time",
    # Plot window ribbon bar
    "plot_ribbon_collapse_tooltip": "Collapse ribbon  (F10)",
    "plot_ribbon_zoom_tooltip": "Reset zoom to fit all data (one-shot)",
    "plot_ribbon_fit_x_tooltip": "Keep X axis fitted to data (disables on manual pan)",
    "plot_ribbon_fit_y_tooltip": "Keep Y axis fitted to data (disables on manual pan)",
    "plot_ribbon_split_y_tooltip": "Separate Y axis per signal",
    "plot_ribbon_graph_settings_tooltip": "Configure grid spacing and legend position",
    "plot_ribbon_dual_cursor_tooltip": "Show a second cursor (B) for measuring intervals",
    "plot_ribbon_follow_tooltip": "Cursor follows the latest data point",
    "plot_ribbon_snap_tooltip": "Snap cursor to nearest sample point",
    "plot_ribbon_fft_tooltip": "Show amplitude spectrum (FFT) of visible signals",
    "plot_ribbon_time_config_tooltip": "Configure time display and timezone",
    # Plot window actions
    "plot_window_title": "Canlytics — Plot",
    "plot_window_add_signal_label": "Signal",
    "plot_window_add_signal_tooltip": "Add signal to plot",
    "plot_window_add_derived_label": "Derived",
    "plot_window_add_derived_tooltip": "Add derived (formula) signal",
    "plot_window_save_config_label": "Save",
    "plot_window_save_config_tooltip": "Save signal configuration to file",
    "plot_window_load_config_label": "Open",
    "plot_window_load_config_tooltip": "Load signal configuration from file",
    "plot_window_append_config_label": "Append",
    "plot_window_append_config_tooltip": "Append signals from another config file",
    "plot_window_rescale_label": "Rescale",
    "plot_window_rescale_tooltip": "Fit all data in view (X and Y)",
    "plot_window_rescale_x_label": "Fit X",
    "plot_window_rescale_x_tooltip": "Keep X axis continuously fitted to all data",
    "plot_window_rescale_y_label": "Fit Y",
    "plot_window_rescale_y_tooltip": "Keep Y axis continuously fitted to data",
    "plot_window_auto_scroll_label": "Live",
    "plot_window_auto_scroll_tooltip": "Auto-scroll to follow incoming live data",
    "plot_window_playback_label": "Playback",
    "plot_window_playback_tooltip": "Show/hide playback bar",
    "plot_window_grid_toggle_label": "Grid",
    "plot_window_grid_toggle_tooltip": "Show/hide grid lines",
    "plot_window_legend_toggle_label": "Legend",
    "plot_window_legend_toggle_tooltip": "Show/hide signal legend",
    "plot_window_y_axis_separate_label": "Split Y",
    "plot_window_y_axis_separate_tooltip": "Separate Y axis per signal",
    "plot_window_fft_label": "FFT",
    "plot_window_fft_tooltip": "Amplitude spectrum of visible signals (use dual cursor to restrict range)",
    "plot_window_cursor_label": "Cursor",
    "plot_window_cursor_tooltip": "Show/hide cursor",
    "plot_window_display_avg": "Show average",
    "plot_window_display_min_max": "Show min / max",
    "plot_window_display_count": "Show count",
    "plot_window_export_image_label": "Export Image",
    "plot_window_export_image_tooltip": "Save plot as PNG image",
    "plot_window_export_csv_label": "Export CSV",
    "plot_window_export_csv_tooltip": "Export signal data to CSV",
    "plot_window_export_image_dialog_title": "Export Plot Image",
    "plot_window_export_image_filter": "PNG Image (*.png);;JPEG Image (*.jpg);;BMP Image (*.bmp)",
    "plot_window_export_failed_title": "Export Failed",
    "plot_window_export_csv_dialog_title": "Export Signal Data",
    "plot_window_export_csv_filter": "CSV Files (*.csv)",
    "plot_window_export_csv_title": "Export CSV",
    "plot_window_export_csv_no_signals": "No signals to export.",
    # Derived signal dialog
    "derived_signal_new_title": "Derived signal",
    "derived_signal_edit_title_prefix": "Edit — {name}",
    "derived_signal_tab_formula": "Formula",
    "derived_signal_tab_style": "Style",
    "derived_signal_tab_filter": "Filter",
    "derived_signal_preview_button": "Preview",
    "derived_signal_name_label": "Name:",
    "derived_signal_name_placeholder": "e.g. rssi_ch1",
    "derived_signal_generated_code_group": "Advanced: generated formula",
    "derived_signal_formula_label": "Formula:",
    "derived_signal_formula_placeholder": "# Write a Python script.\n# Assign:  result = (ts_array, y_array)\n",
    "derived_signal_signal_list_label": "Signals in this plot (double-click to insert):",
    "derived_signal_basic_mode_blocked_title": "Cannot switch to Basic mode",
    "derived_signal_basic_mode_blocked_message": (
        "This formula uses custom logic that cannot be represented in "
        "Basic mode.\nContinue editing it in Advanced mode."
    ),
    "derived_signal_config_error_prefix": "# Config error: {error}",
    "derived_signal_preview_config_error_prefix": "Config error: {error}",
    "derived_signal_preview_empty_formula": "Formula is empty.",
    "derived_signal_preview_unexpected_error_prefix": "Unexpected error: {error}",
    "derived_signal_preview_empty_result": "Result: (empty)",
    "derived_signal_preview_result_prefix": "Result ({count} points): {sample}{ellipsis}",
    "derived_signal_name_conflict_title": "Name conflict",
    "derived_signal_name_conflict_message": "'{name}' is already used by a regular signal.",
    "derived_signal_duplicate_name_title": "Duplicate name",
    "derived_signal_duplicate_name_message": "A derived signal named '{name}' already exists.",
    "derived_signal_mode_basic": "Basic",
    "derived_signal_mode_advanced": "Advanced",
    "candidate_no_signals_title": "No signals",
    "candidate_no_signals_message": "Calculate candidate signals first before searching.",
    "realtime_details_id_placeholder": "ID -",
    "realtime_details_id_prefix": "ID {id}",
    "realtime_unique_values_per_byte": "Unique values per byte",
    "realtime_highlight_hold_label": "Highlight Hold",
    "realtime_details_label": "Details",
    "realtime_change_detection_off": "Change detection OFF",
}
