UI_STRINGS = {
    "dbc_manager_title": "DBC Manager",
    "dbc_empty": "No DBC loaded",
    "dbc_enable_header": "Enable",
    "dbc_name_header": "DBC",
    "dbc_type_header": "Type",
    "dbc_load": "Load DBC...",
    "dbc_delete": "Delete DBC",
    "dbc_load_title": "Load DBC",
    "dbc_files_filter": "DBC files (*.dbc);;All files (*)",
    "dbc_loading": "Loading DBC...",
    "dbc_loading_title": "Loading",
    "dbc_load_failed_title": "DBC load failed",
    "dbc_load_failed_message": "Unable to load DBC:\n{error}",
    "graph_settings_title": "Graph settings",
    "graph_settings_signal_tab": "Signal",
    "graph_settings_graph_tab": "Graph",
    "graph_settings_filters_tab": "Filters",
    "ok": "OK",
    "invalid_name_title": "Invalid name",
    "invalid_name_message": "Signal name cannot be empty.",
    "duplicate_signal_title": "Duplicate signal",
    "duplicate_signal_message": "A signal named '{name}' already exists.",
    "signal_filter_title": "Signal filter",
    "filter_type_label": "Filter type",
    "window_label": "Window (MA/Median/SG)",
    "alpha_label": "Alpha (EMA)",
    "sigma_label": "Sigma (Gaussian)",
    "polyorder_label": "Polyorder (Savitzky-Golay)",
    "graph_style_title": "Graph style",
    "select_color": "Select color",
    "color_label": "Color",
    "line_style_label": "Line style",
    "line_width_label": "Line width",
    "decode_dbc_group_title": "DBC",
    "decode_group_title": "CAN decode",
    "dbc_label": "DBC",
    "message_label": "Message",
    "signal_label": "Signal",
    "value_label": "Value",
    "apply_dbc": "GetDecode",
    "show_all_ids": "Show all IDs",
    "signal_name_label": "Signal name",
    "can_id_label": "CAN ID",
    "source_label": "Source",
    "match_mode_label": "Match mode",
    "pgn_label": "PGN",
    "start_bit_label": "Start bit",
    "length_label": "Length",
    "endianness_label": "Endianness",
    "data_type_label": "Data type",
    "scale_label": "Scale",
    "offset_label": "Offset",
    "mux_start_label": "MUX Start",
    "mux_bytes_label": "MUX bytes",
    "mux_value_label": "MUX value",
    "little_endian": "Little Endian",
    "big_endian": "Big Endian",
    "add_new_graph": "Add new graph",
    "add_last_graph": "Add last graph",
    "main_window_title": "CAN Log Viewer",
    "load_log_title": "Load CAN log",
    "append_log_title": "Append CAN log",
    "log_files_filter": "Log files (*.log *.txt);;All files (*)",
    "loading_log": "Loading CAN log...",
    "loading_title": "Loading",
    "failed_prefix": "Failed: {error}",
    "cancel": "Cancel",
    "menu_file": "File",
    "menu_load_log": "Load Log",
    "menu_append_log": "Append Log",
    "menu_clear_log": "Clear log",
    "menu_load_dbc": "Load DBC...",
    "menu_settings": "Settings",
    "menu_time_config": "TimeConfig...",
    "menu_tools": "Tools",
    "menu_add_plot": "Add new graphic window",
    "menu_ssh_connection": "SSH Connection...",
    "select_all": "Select all",
    "select_none": "Select none",
    "interpret_frames": "Interpret frames",
    "interpret_tooltip": "Load/enable a DBC to interpret frames",
    "expand_all": "Expand all",
    "collapse_all": "Collapse all",
    "ssh_connection_title": "SSH Connection",
    "ssh_host_placeholder": "192.168.x.x",
    "ssh_username_default": "root",
    "ssh_key_placeholder": "Select private key file",
    "ssh_browse": "Browse",
    "ssh_start": "Start",
    "ssh_stop": "Stop",
    "ssh_status_idle": "Idle",
    "ssh_ip_host_label": "IP/Host",
    "ssh_username_label": "Username",
    "ssh_key_file_label": "Key file",
    "ssh_key_passphrase_label": "Key passphrase",
    "ssh_can_interface_label": "CAN interface",
    "ssh_status_label": "Status",
    "ssh_select_key_title": "Select private key",
    "ssh_key_files_filter": "Key files (*);;All files (*)",
    "ssh_host_required": "Host required",
    "ssh_error_prefix": "Error: {error}",
}
